### ISSUE TITLE
Ability to archive entities

### ISSUE THREAD

**Issue by nylonee** [MicrosoftTCE/civic-graph-API#11]
It would be nice to have a way of archiving entities, rather than deleting them outright. Only admins will be able to archive entities via the admin panel, but once archived they won't show up on the graph.

My thinking through this implementation is to add a new field to each entity: the 'active' column. When an entity is active it will show up on the network, but when it is inactive it won't be rendered. Admins will be able to see both active and inactive entities, and toggle archive status.

**Comment by nylonee** [comment]
To add this implementation, it's likely that we'll have to use a tool for migrations. the [Flask-Migrate](https://github.com/miguelgrinberg/Flask-Migrate) tool is a good start for this, and will allow us to further modify the database with ease down the road

**Comment by brianavecchione** [comment]
Implemented via two features 
- Slider on CG home showing entities with connections > 2
- Check-in application which populates its own instance of the graph per deployment
