### ISSUE TITLE
Adding explanatory documentation 

### ISSUE THREAD

**Issue by maecapozzi** [MicrosoftTCE/civic-graph-API#13]
While this graph is clear and useful, I think a bit more documentation would about exactly what the graph is representing and ways that it can be used would benefit new users. 

My suggestion is to add another window like the one that opens when the user clicks "Learn More." It might get users up and running more quickly, and will encourage them to engage with the site.

**Comment by nylonee** [comment]
Very good point.
The 'learn more' is only showing up on the desktop version of civicgraph.io, it probably would require a bit of thinking through how such an 'about' page can be implemented in both desktop and mobile.

**Comment by brianavecchione** [comment]
Redefined in #79
