### ISSUE TITLE
Implement Sharing Info

### ISSUE THREAD

**Issue by hhassan1230** [MicrosoftTCE/civic-graph-API#14]
On index.html add lines:
`<meta content="The Civic Graph" name="application-name">
    <meta content="Civic Graph" property="og:title">
    <meta content="Learn who is who in civic tech with The Civic Graph by Microsoft" property="og:description">
    <meta content='img/CivicgraphImg.png' property="og:image">
    <meta content="The Civic Graph" property="og:site_name">`
into head and this png into img folder.
![civicgraphimg](https://cloud.githubusercontent.com/assets/9095253/15417655/55a645f6-1e26-11e6-9da6-3392f37d4fab.png)
I do not have permission to make a pull request to this open source project.

**Comment by brianavecchione** [comment]
Added

**Comment by hhassan1230** [comment]
Hey @brianavecchione good working the title and description is there. 
However, the image is not showing up. This is more than like due to the url path not being correct. 
I do not have access to the repo to fix this, but when your team has time check on this tag:
1. make sure the image is in the img directory
2 . the image is named CivicgraphImg.png
3. make sure the content url location (content='img/CivicgraphImg.png') is point to the CivicgraphImg.png correctly.
4. Resources: https://developers.facebook.com/docs/sharing/best-practices
<meta content='img/CivicgraphImg.png' property="og:image">
