### ISSUE TITLE
minor glitches in install

### ISSUE THREAD

**Issue by Alg0rhythm** [MicrosoftTCE/civic-graph-API#5]
Dunno the outcome, yet,. Also it seems like file folder placement might cause some complications with the install instructions, but overall, relatively well written.

![install screen shot](https://cloud.githubusercontent.com/assets/806337/11944849/3ac8568c-a817-11e5-8e17-c74cc4e69957.GIF)

**Comment by Alg0rhythm** [comment]
Yeah, from there I am running the run.py and getting an error message, specifically Import Error: no module called Flask

**Comment by nylonee** [comment]
Is pip installing Flask to the right python version?
Run `pip -V` to ensure that it's installing to the same python version that you're using.
