### ISSUE TITLE
Receiving consistent 500 on /api/entities request

### ISSUE THREAD

**Issue by afomi** [MicrosoftTCE/civic-graph-API#86]
![civic500](https://user-images.githubusercontent.com/67984/30942078-9b992148-a39d-11e7-8ba5-4bdfd8be0e73.png)

Yet, /api/categories works.

**Comment by seerocode** [comment]
Issue may have been related to API validation failure when field for employment was left empty on frontend user submission. 

Validation has been added to resolve to NONE if no employment is entered.

**Comment by afomi** [comment]
the response looks good now. thanks!
